//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Za_Ro
{
    using System;
    using System.Collections.Generic;
    
    public partial class volim
    {
        public int idPoruka { get; set; }
        public System.DateTime datum { get; set; }
        public string poruka { get; set; }
    }
}
